id: AB663A894
base_file: f97F2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:06:26.355596
  last_modified_at: 2022-06-05 20:06:26.355605
